spring:
  application:
    name: ibx-cloud-gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: ibx-cloud-account
          uri: lb://ibx-cloud-account
          predicates:
            - Path=/account/*/user/**
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: client1
            client-secret: T7OI3uwvK6AHHPNobZL8YSGUXvbZwU2J
            scope: openid,profile,email
            authorization-grant-type: authorization_code
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/realm1



server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/