spring:
  application:
    name: ibx-cloud-gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: ibx-cloud-account
          uri: lb://ibx-cloud-account
          predicates:
            - Path=/ibx/*/user/**


server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka/