spring:
  application:
    name: ibx-cloud-account
  webflux:
    base-path: /
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: ibx-account
      authentication-database: admin
      username: mongoadmin
      password: mongoadmin
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 5
      properties:
        retry:
          backoff.ms: 1000

server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://89.117.61.23:8761/eureka/

app:
  kafka:
    topic:
      delete-account: ibx.delete-account