spring:
  application:
    name: ibx-cloud-account
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/ibx-account

server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/