spring:
  application:
    name: ibx-cloud-account
  webflux:
    base-path: /
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: ibx-account
      authentication-database: admin
      username: mongoadmin
      password: mongoadmin

server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://89.117.61.23:8761/eureka/