spring:
  application:
    name: ibx-cloud-account
  data:
    mongodb:
      uri: mongodb://ibx-account@localhost:27017/?retryWrites=true&loadBalanced=false&serverSelectionTimeoutMS=5000&connectTimeoutMS=10000&authSource=admin&authMechanism=SCRAM-SHA-256&3t.uriVersion=3&3t.connection.name=LOCAL&3t.alwaysShowAuthDB=true&3t.alwaysShowDBFromUserRole=true
      username: admin
      password: admin

server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/