spring:
  application:
    name: ibx-cloud-account
  data:
    mongodb:
      host: host.docker.internal
      port: 27017
      database: ibx-account
      username: admin
      password: admin

server:
  port: 9100

eureka:
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka/